services:
  langfuse-db:
    image: postgres:13
    container_name: langfuse-postgres
    environment:
      POSTGRES_DB: langfuse
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
    volumes:
      - langfuse-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks: [app-net]

  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse
    environment:
      DATABASE_URL: "postgresql://langfuse:langfuse@langfuse-db:5432/langfuse"
      NEXTAUTH_URL: "http://localhost:3001"
      NEXTAUTH_SECRET: "mysecret"
      SALT: "mysalt"
      ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
      LANGFUSE_INIT_ORG_ID: "voice-demo-org"
      LANGFUSE_INIT_ORG_NAME: "Voice Demo Organization"
      LANGFUSE_INIT_PROJECT_ID: "voice-demo-project"
      LANGFUSE_INIT_PROJECT_NAME: "Voice Demo Project"
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: "pk-lf-voice-demo-key"
      LANGFUSE_INIT_PROJECT_SECRET_KEY: "sk-lf-voice-demo-secret"
      LANGFUSE_INIT_USER_EMAIL: "admin@observe.com"
      LANGFUSE_INIT_USER_NAME: "Voice Demo Admin"
      LANGFUSE_INIT_USER_PASSWORD: "observe123"
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "3001:3000"
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  langfuse-pgdata: